name: Diff Workflow

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
      
      - name: install gitpython
        run: |
          pip install deepdiff

      - name: install gitpython
        run: |
          pip install diff-match-patch

      - name: install gitpython
        run: |
          pip install python-dotenv

      - name: Install openai package
        run: |
          pip install openai

      - name: Set up git configs
        run: |
          git rev-parse --abbrev-ref HEAD
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git config --global credential.helper cache

      - name: Get redcap protocol
        run: |
          git clone --depth 1 https://${{ secrets.AUTH }}@github.com/sensein/b2ai-redcap2rs
          mkdir redcap_protocol
          cp -r b2ai-redcap2rs/activities/* ./redcap_protocol
      
      - name: Get mood protocol
        run: |
          git clone --depth 1 https://${{ secrets.AUTH }}@github.com/sensein/b2aiprotocol 
          mkdir mood_protocol
          cp -r b2aiprotocol/mood/* ./mood_protocol
          cp -r b2aiprotocol/generic/* ./mood_protocol
          ls ./mood_protocol
          rm -r ./mood_protocol/picture_description/

      - name: Get GED7 and PHQ-9
        run: |
          git clone --depth 1 https://${{ secrets.AUTH }}@github.com/ReproNim/reproschema-library/
          mkdir mood_protocol
          cp -r reproschema-library/activities/PHQ-9/ ./mood_protocol
          cp -r reproschema-library/activities/GAD7/ ./mood_protocol

      - name: Set up .env
        run: |
          echo "OPENROUTER_API_KEY=${{ secrets.OPENROUTER_KEY }}" >> .env

      - name: Run Bash Script
        run: |
          bash job.sh

      - name: Commit reproschema
        run: |
          git add individual-file-diffs
          git add diff.html
          git commit -a -m "$(date): Diff Generated"
          git push
